services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - app-node-modules:/workspaces/app/node_modules
      - claude-code-config:/home/node/.claude
    command: sleep infinity
    environment:
      TZ: Asia/Tokyo

volumes:
  app-node-modules:
  claude-code-config:
